config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  root :to => 'users#start'
  # end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get 'home/about' => 'users#about'
  # resources :books 下記に書換え
  # 単数にするとそのコントローラのidがリクエストに含まれなくなる。
  # 今回、post_commentsのshowページは必要ない（コメントの詳細ページは作成しない）
  # ため、idを受け渡す必要がなくresource。
  resources :books do
    # sをつける今回はidの詳細の情報が必要なので
    resources :post_comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
	has_many :post_comments, dependent: :destroy
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates :comment, presence: true, length: { maximum: 15 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 	devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
    attachment :profile_image
    has_many :books, dependent: :destroy
    # コメント機能を利用する際のアソシエーション
    has_many :post_comments, dependent: :destroy

    validates :name, presence: true, length: { minimum: 2, maximum: 20 }
    validates :introduction, length: { maximum: 50 }

	# deviseでemailを不必要にする
	def email_required?
	false
	end
	def email_changed?
	false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	# protected
	# def configure_permitted_parameters
	# 	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	# end


	def after_sign_in_path_for(resource)
	user_path(resource) # ログイン後に遷移するpathを設定
	end
	def after_sign_out_path_for(resource)
	root_path(resource) # ログアウト後に遷移するpathを設定
	end


	protected
	def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # ログインしてる時だけ許可するアクションをonlyで指定
  before_action :authenticate_user!, only: [:index,:show,:edit,:create,:update,:destroy]

  def index
  	@book = Book.new
  	@books = Book.all
    # 全部を表示するだけなので紐付け不要
    @user = current_user
  end

  def show
    @book = Book.new
  	@book_show = Book.find(params[:id])
    @user = User.find(@book_show.user_id)

    @post_comment = PostComment.new
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def create
    @user = current_user
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    @users = User.all
    if
      @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if
      @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'edit'
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
    flash[:notice] = "You have destroyed book successfully."
  	redirect_to books_path
  end

  def start
  end

	private

	def book_params
	  params.require(:book).permit(:title, :body)
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    if
    comment.save
    flash[:notice] = "You have creatad comment successfully."
	else
	flash[:notice] = "1-15 Moji !!!"
	end
	redirect_to book_path(book)
end

def show
end

def destroy
	# destroyのURLで2個のidを渡してあげる必要があるので指定してあげる
    @book = Book.find(params[:book_id])
    @comment = PostComment.find(params[:id])
    # ここで一致するかを確認している記述
    # book_idはPostCommentテーブルの中のカラムでBook.idはBookテーブルのidってこと
    @comment.book_id = @book.id
    @comment.destroy
    flash[:notice] = "You have destroyed comment successfully."
	redirect_to book_path(@book)
end

def edit
	@book = Book.find(params[:book_id])
    @comment = PostComment.find(params[:id])
end

def update
    @book = Book.find(params[:book_id])
    @comment = PostComment.find(params[:id])
    if
    @comment.update(post_comment_params)
    flash[:notice] = "You have updated successfully."
    redirect_to book_path(@book.id)
    else
    render 'edit'
    end
end

	private
	def post_comment_params
	  params.require(:post_comment).permit(:user_id,
	                      :book_id,
	                      :comment)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# ログインしてる時だけ許可するアクションをonlyで指定
	before_action :authenticate_user!, only: [:index,:show,:edit,:update]


	def index
		@users = User.all
		@book = Book.new
		@user = current_user
		@books = @user.books.reverse_order
	end

	def new
		@user = User.new
	end

	def show
		@book = Book.new
		@user = User.find(params[:id])
		# 紐付けしてる
		@books = @user.books.reverse_order
	end

	def edit
		@user = User.find(params[:id])
		# カレントユーザーでない場合
	    if @user != current_user
	      redirect_to user_path(current_user.id)
	    end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "You have updated user successfully."
			redirect_to user_path(@user.id)
		else
			render 'edit'
		end
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if
			@book.save
			flash[:notice] = "Welcome! You have signed up successfully."
			redirect_to book_path(@book.id)
		else
			@books = Book.all
			render 'index'
		end
	end

	def start
	end

	def about
	end

	private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">


	<% if @book.errors.any? %>
	<h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
	<% @book.errors.full_messages.each do |message| %>
	<%= message %>
	<% end %>
	<% end %>


	<div class='col-md-6 col-md-offset-3'>

		<h1>Editing Book</h1>
		<!-- form_for部分 -->
		<%= form_for(@book) do |f| %>

		<div class="row">
			<label>Title</label>
			<%= f.text_field :title, class:"col-xs-12 book_title" %>
		</div>
		<div class="row">
			<h4>Opinion</h4>
			<%= f.text_area :body, class:"col-xs-12 book_body"%>
		</div>
		<div class="row">
			<%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
		</div>
		<% end %>

		<%= link_to "Show", book_path(@book.id) %> |
		<%= link_to "Back", books_path %>

	</div>
</div>

app/views/books/index.html.erb
<div class="container">

<%= render 'users/template', user: @user, book: @book %>


  <!-- <div class="row"> -->
    <div class="col-xs-9">

      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>opinion</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <!-- book.userで紐付けしている -->
            <td><%= attachment_image_tag book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>

            <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </td>

            <td><%= book.body %></td>

          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  <!-- </div> -->
</div>

<!-- コメント件数を表示 -->

app/views/books/show.html.erb
<div class="container">

	<%= render 'users/template', user: @user, book: @book %>

	<div class="col-xs-9">
		<h2>Book detail</h2>
		<table class='table'>

			<tr>
				<td><%= attachment_image_tag @user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>

	            <br>
	            <%= link_to user_path(@user.id) do %>
	            <%= @book_show.user.name %>
	            <% end %>
	            </td>

				<td>
	            <%= link_to book_path(@book_show.id) do %>
				<%= @book_show.title %>
				<% end %>
				</td>

				<td><%= @book_show.body %></td>


				<% if @user == current_user %>
				<td><%= link_to "Edit", edit_book_path(@book_show.id),class:"btn-sm btn-success" %></td>
				<td><%= link_to "Destroy", book_path(@book_show.id),class:"btn-sm btn-danger", method: :delete,data: { confirm: '本当に消しますか？' } %></td>
				<% end %>
			</tr>
		</table>
	</div>

<!-- コメント部分 -->
<div class="col-xs-9">
<h2>Comments</h2>

<!-- 件数の表示 -->
<h4 class="comment-count"><%= @book_show.post_comments.count %>件コメント</h4>

<!-- コメント本文の表示部分 -->
<div class="row">
	<div class="col-xs-12">
		<table class='table'>
			<% @book_show.post_comments.each do |post_comment| %>
			<tr>
				<td>
					<a href="#" class="link-author"><%= post_comment.user.name %></a>
				</td>
				<td>
					<span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
				</td>
				<td>
					<div class="comment-entry"><%= post_comment.comment %></div>
				</td>
				<td>
					<%= link_to "Edit",  edit_book_post_comment_path(@book_show, post_comment.id),class:"btn-sm btn-info" %>
				</td>
				<td>
					<%= link_to "Destroy", book_post_comment_path(@book_show, post_comment.id),class:"btn-sm btn-warning", method: :delete,data: { confirm: '本当に消しますか？' } %>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

<!-- コメント入力フォーム -->
<!-- ルーティングもネスト（親子関係）しているため、上記2つの情報が必要。-->
<%= form_for [@book_show, @post_comment] do |f| %>
    <div class="row">
        <div class="col-xs-9">
            <%= f.text_area :comment, rows:'1', class: "form-control",placeholder: "コメントをここに" %>
        </div>
		<div class="col-xs-3">
	    <%= f.submit "post", class:"btn btn-primary" %>
	    </div>
    </div>
<% end %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>
  <header class="navbar navbar-inverse">
    <div class="container">
      <!-- <div class="row"> -->
        <nav class='nav navbar-nav navbar-left' >
          <span>Bookers</span>
        </nav>
        <nav class="nav navbar-nav navbar-right">
          <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
            <% if user_signed_in? %>
            <!-- ログインしてる時 -->
            <li class="nav-list-item">
            <%= link_to user_path(current_user) do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true"> Home </span>
            <% end %>
            </li>

            <li class="nav-list-item">
            <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user" aria-hidden="true"> Users </span>
            <% end %>
            </li>

            <li class="nav-list-item">
            <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book" aria-hidden="true"> Books </span>
            <% end %>
            </li>

            <li class="nav-list-item">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout </span>
            <% end %>
            </li>

            <% else %>

            <li class="nav-list-item">
            <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true"> Home </span>
            <% end %>
            </li>

            <li class="nav-list-item">
            <%= link_to home_about_path do %>
              <span class="glyphicon glyphicon-link" aria-hidden="true"> About </span>
            <% end %>
            </li>

            <li class="nav-list-item">
            <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit" aria-hidden="true"> sign up </span>
            <% end %>
            </li>

            <li class="nav-list-item">
            <%= link_to user_session_path do %>
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"> login </span>
            <% end %>
            </li>
            <% end %>
          </nav>
        </ul>
      </div>
      <!-- </div> -->
    </div>
  </header>
  <div class="container">
  <% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
  <% end %>
  </div>
  <%= yield %>
</body>
</html>

app/views/post_comments/edit.html.erb
<div class="container">

	<% if @comment.errors.any? %>
	<h2><%= @comment.errors.count %>errors prohibited this book from being saved:</h2>
	<% @comment.errors.full_messages.each do |message| %>
	<%= message %>
	<% end %>
	<% end %>

	<div class='col-md-6 col-md-offset-3'>

		<h1>Editing Comment</h1>
		<!-- form_forだとcreateアクションにデフォルトで繋がるので指定先を変えてあげる -->
		<!-- createアクションの@commentを探しに行ってる状態 -->
		<%= form_for @comment,url:book_post_comment_path(@book.id) do |f| %>

		<div class="row">
			<label>Title</label>
			<%= f.text_field :comment, class:"col-xs-12 book_title" %>
		</div>

		<div class="row">
			<%= f.submit 'Update', class:"btn btn-primary col-xs-12" %>
		</div>
		<% end %>

	</div>
</div>

app/views/users/_template.html.erb
<%= form_for(book) do |f| %>
<% if book.errors.any? %>
<h2><%= book.errors.count %>errors prohibited this book from being saved:</h2>
<% book.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<div class="col-xs-3">
    <h2>User info</h2>
    <table class='table'>
        <tr>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        </tr>
        <tr>
            <th>name</th>
            <th><%= user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
        </tr>
    </table>

    <div class="row">
            <%= link_to "", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>




    <h2>New book</h2>

    <div class="field row">
        <label>Title</label>

        <%= f.text_field :title, class:"col-xs-12" %>
    </div>

    <div class="field row">
        <label>Opinion</label>

        <%= f.text_area :body, class:"col-xs-12" %>
    </div>
    <div class="row">
        <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
    </div>
    <% end %>
</div>

app/views/users/about.html.erb
<div class='body'>
	<div class='container'>

		<p id="notice"></p>


		<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>


	</div>
</div>

<footer>
	<div class='container'>
		<div class='row'>
			<div class='col-xs-3 col-xs-offset-9'>
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>

app/views/users/edit.html.erb
<h2>User info</h2>

<% if @user.errors.any? %>
<h2><%= @user.errors.count %>errors prohibited this book from being saved:</h2>
<% @user.errors.full_messages.each do |message| %>
        <%= message %>
<% end %>
<% end %>




<%= form_for(@user) do |f| %>
<label>Name</label>
<%= f.text_field :name, autofocus: true, placeholder:"名前"%>
</br>
<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
</br>
<label>ProfileImage</label>
<%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
</br>
<label>Introduction</label>
<%= f.text_field :introduction, autofocus: true %>
</br>
<%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">

<!-- ここに追加 -->
<%= render 'users/template', user: @user, book: @book %>


<div class='col-xs-9'>
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/users/show.html.erb
<div class="container">

<!-- ここに追加 -->
<%= render 'users/template', user: @user, book: @book %>

<div class='col-xs-9'>
<h2>Books</h2>

<table class='table table-hover table-inverse'>

  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= attachment_image_tag @user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
      <td>
        <%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
      </td>

      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/start.html.erb
<!-- <h1 class="jquery">Hello jQuery!</h1> -->
<div id="container">
	<div id="theTarget">
		<div class="image1"></div>
		<div class="image2"></div>
		<div class="image3"></div>
		<div class="image4"></div>
		<div class="image5"></div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class='top-message col-md-offset-3 col-md-6'>

			<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>
			<div class="row">
				<%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
			</div>
			<div class="row">
				<%= link_to "Sign in", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
			</div>
		</div>
	</div>
</div>


<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>